# This yaml describes our current checks.
#   Any checks marked "# TODO: RWC" are "re-enable when corrected.RWC" are "re-enable when corrected.
AllCops:
  TargetRubyVersion: 2.5

Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/WordArray:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
