AllCops:
  Exclude:
    - "bin/**"
    - "vendor/bundle/**/*"
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile

Style/Documentation:
  Exclude:
    - config/application.rb

Style/ExpandPathArguments:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude:
    - config/puma.rb

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false
