---
registry:
  - namespace:
      path:
        - :dchbx
        - :enroll_app
        - :aca_shop_market
      meta:
        label: ACA Shop
        content_type: :feature_list
        description: 'ACA Shop Market Settings'
        is_required: true
        is_visible: true
    features:
      - key: :health_packages
        is_enabled: true
        item: :features_display
        meta:
          label: Health Packages
          content_type: :nav
          default: :''
          description: 'Configurations for Health Product Packages'
          is_required: true
          is_visible: true
        settings:
          - key: :product_packages
            item:
              - :health_product_package_2021
              - :health_product_package_2020
            meta:
              label: Product Packages
              content_type: :feature_group
              description: product packages
              is_required: false
              is_visible: true
  - namespace:
    - :dchbx
    - :enroll_app
    - :aca_shop_market
    - :health_product_packages
    features:
      - key: :shop_product_package_clone
        item: ResourceRegistry::Operations::Features::Clone.new
        is_enabled: true
        meta:
          label: Shop Product Package Clone
          content_type: :legend
          default: nil
          description: Clone shop product packages
          is_required: false
          is_visible: true
        settings:
          - key: :calender_year 
            item: nil
            meta:
              label: Calender Year
              content_type: :select
              description: Choose calender year for new product package
              enum: <%= [Date.today.year + 1, Date.today.year + 2].reduce([]) {|values, date| values << [date, date]} %>
              is_required: false
              is_visible: true
      - key: :health_product_package_2021
        is_enabled: true
        item: :feature_collection
        meta:
          label: Health Product Package 2021
          content_type: :legend
          default: true
          description: Health Product Pacakge for 2021
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_models
            item:
              - :initial_sponsor_jan_default_2021
              - :initial_sponsor_default_2021
              - :renewal_sponsor_jan_default_2021
              - :renewal_sponsor_default_2021
            meta:
              label: Contribution Models
              content_type: :feature_list_panel
              description: Contribution Models
              is_required: false
              is_visible: true
          - key: :clone
            item: "/exchanges/configurations/shop_product_package_clone/edit"
            meta:
              label: Clone Product Package
              content_type: :feature_action
              description: Clone Product Packages for the given calender year
              is_required: false
              is_visible: true
      - key: :health_product_package_2020
        is_enabled: true
        item: :feature_collection
        meta:
          label: Health Product Package 2020
          content_type: :legend
          default: true
          description: Health Product Pacakge for 2020
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_models
            item:
              - :initial_sponsor_jan_default_2020
              - :initial_sponsor_default_2020
              - :renewal_sponsor_jan_default_2020
              - :renewal_sponsor_default_2020
            meta:
              label: Contribution Models
              content_type: :feature_list_panel
              description: Contribution Models
              is_required: false
              is_visible: true
  - namespace:
    - :enroll_app
    - :aca_shop_market
    - :benefit_market_catalog
    - :catalog_2021
    - :contribution_model_criteria
    features:
      - key: :initial_sponsor_jan_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        meta:
          label: 2021 Initial Sponsor January Default
          content_type: :legend
          default: true
          description: Contribution Criteria for January 2021 Initial Sponsors
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
            meta:
              label: Contribution Model Key
              content_type: :select
              description: Enter contribution model key
              enum: [{zero_percent_sponsor_fixed_percent_contribution_model: "Zero Percent Sponsor Fixed Percent Contribution Model"}, {fifty_percent_sponsor_fixed_percent_contribution_model: "Fifty Percent Sponsor Fixed Percent Contribution Model"}]
              is_required: true
              is_visible: true
          - key: :benefit_application_kind
            item: :initial
            meta:
              label: Benefit Application Kind
              content_type: :select
              enum: [{initial: "Initial"}, {renewal: "Renewal"}]
              default: ''
              description: Enter benefit application kind
              is_required: true
              is_visible: true
          - key: :effective_period
            item: <%= Date.new(2021,1,1)..Date.new(2021,1,31) %>
            meta:
              label: Effective Period
              content_type: :date_range
              description: Please enter effective period for the contribution model
              is_required: true
              is_visible: true
          - key: :order
            item: 1
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :initial_sponsor_jan_default
            meta:
              label: Renewal Criterion Key
              content_type: :text_field
              description: Enter renewal criterion key
              is_required: false
              is_visible: true
      - key: :initial_sponsor_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        meta:
          label: 2021 Initial Sponsor Default
          content_type: :legend
          default: true
          description: Contribution Criteria for 2021 Initial Sponsors
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
            meta:
              label: Contribution Model Key
              content_type: :select
              description: Enter contribution model key
              enum: [{zero_percent_sponsor_fixed_percent_contribution_model: "Zero Percent Sponsor Fixed Percent Contribution Model"}, {fifty_percent_sponsor_fixed_percent_contribution_model: "Fifty Percent Sponsor Fixed Percent Contribution Model"}]
              is_required: true
              is_visible: true
          - key: :benefit_application_kind
            item: :initial
            meta:
              label: Benefit Application Kind
              content_type: :select
              enum: [{initial: "Initial"}, {renewal: "Renewal"}]
              default: ''
              description: Enter benefit application kind
              is_required: true
              is_visible: true
          - key: :effective_period
            item: <%= Date.new(2021,2,1)..Date.new(2021,12,31) %>
            meta:
              label: Effective Period
              content_type: :date_range
              description: Please enter effective period for the contribution model
              is_required: true
              is_visible: true
          - key: :order
            item: 3
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :initial_sponsor_default
            meta:
              label: Renewal Criterion Key
              content_type: :text_field
              description: Enter renewal criterion key
              is_required: false
              is_visible: true
      - key: :renewal_sponsor_jan_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        meta:
          label: 2021 Renewal January Sponsor Default
          content_type: :legend
          default: true
          description: Contribution Criteria for January 2021 Renewal Sponsors
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
            meta:
              label: Contribution Model Key
              content_type: :select
              description: Enter contribution model key
              enum: [{zero_percent_sponsor_fixed_percent_contribution_model: "Zero Percent Sponsor Fixed Percent Contribution Model"}, {fifty_percent_sponsor_fixed_percent_contribution_model: "Fifty Percent Sponsor Fixed Percent Contribution Model"}]
              is_required: true
              is_visible: true
          - key: :benefit_application_kind
            item: :renewal
            meta:
              label: Benefit Application Kind
              content_type: :select
              enum: [{initial: "Initial"}, {renewal: "Renewal"}]
              default: ''
              description: Enter benefit application kind
              is_required: true
              is_visible: true
          - key: :effective_period
            item: <%= Date.new(2021,1,1)..Date.new(2021,1,31) %>
            meta:
              label: Effective Period
              content_type: :date_range
              description: Please enter effective period for the contribution model
              is_required: true
              is_visible: true
          - key: :order
            item: 4
          - key: :default
            item: false
          - key: :renewal_criterion_key
            item: :renewal_sponsor_jan_default
            meta:
              label: Renewal Criterion Key
              content_type: :text_field
              description: Enter renewal criterion key
              is_required: false
              is_visible: true
      - key: :renewal_sponsor_default_2021
        item: :contribution_model_criterion
        is_enabled: true
        meta:
          label: 2021 Renewal Sponsor Default
          content_type: :legend
          default: true
          description: Contribution Criteria for 2021 Renewal Sponsors
          is_required: true
          is_visible: true
        settings:
          - key: :contribution_model_key
            item: :zero_percent_sponsor_fixed_percent_contribution_model
            meta:
              label: Contribution Model Key
              content_type: :select
              description: Enter contribution model key
              enum: [{zero_percent_sponsor_fixed_percent_contribution_model: "Zero Percent Sponsor Fixed Percent Contribution Model"}, {fifty_percent_sponsor_fixed_percent_contribution_model: "Fifty Percent Sponsor Fixed Percent Contribution Model"}]
              is_required: true
              is_visible: true
          - key: :benefit_application_kind
            item: :renewal
            meta:
              label: Benefit Application Kind
              content_type: :select
              enum: [{initial: "Initial"}, {renewal: "Renewal"}]
              default: ''
              description: Enter benefit application kind
              is_required: true
              is_visible: true
          - key: :effective_period
            item: <%= Date.new(2021,2,1)..Date.new(2021,12,31) %>
            meta:
              label: Effective Period
              content_type: :date_range
              description: Please enter effective period for the contribution model
              is_required: true
              is_visible: true
          - key: :order
            item: 2
          - key: :default
            item: true
          - key: :renewal_criterion_key
            item: :renewal_sponsor_default
            meta:
              label: Renewal Criterion Key
              content_type: :text_field
              description: Enter renewal criterion key
              is_required: false
              is_visible: true